### ISSUE TITLE
QuickMultiAttributeEdit-plugin fails to load on Ubuntu 12.10 QgisMaster (1.9)

### ISSUE THREAD

**Issue by guusvandenberg** [lucadelu/QuickMultiAttributeEdit#7]
Hi,

I'm having trouble loading the above-mentioned plugin. When I haven't started a project yet, I get a perfectly normal GUI. However, in an active project I get the following 
message:

```
            Python Error

            Traceback (most recent call last):
            File "/home/guus/.qgis2/python/plugins/QuickMultiAttributeEdit
```

/quickmultiattributeedit_menu.py", line 42, in update_selected
                dialog = quickmultiattributeedit_update_selected_dialog(self.iface)
                File "/home/guus/.qgis2/python/plugins/QuickMultiAttributeEdit/quickmultiattributeedit_dialogs.py", line 60, in **init**
                for (f_index, f) in fields.iteritems():
                AttributeError: 'QgsFields' object has no attribute 'iteritems

I put the issue on the Qgis User List. Etienne Tourigny answered me this:

The plugin has to be updated to the v2 api. Add a new issue to the plugin's bugtracker.

Cheers,

Guus van den Berg

**Comment by marcobra** [comment]
already solved... 

Luca please close this issue report mark it as solved... Thank
